title: Short Biology Notes
description: Short notes on biology.
theme: just-the-docs

url: https://chengjunyuan.github.io/short-biology-notes

aux_links:
  Template Repository: https://github.com/just-the-docs/just-the-docs-template

kramdown:
  math_engine: null
